### PR TITLE
Updates to CHANGELOG and README following SCM collection type update

### PR DESCRIPTION
**Pull request by annelo-msft**
Follow-ups to https://github.com/openai/openai-dotnet/pull/105

### CODE REVIEW

**Comment by eliasandronicou** [comment]
Hello, is the issue solved? I am getting this error in every Assistant's example.
Error (active)	CS7069	Reference to type 'AsyncPageableCollection<>' claims it is defined in 'System.ClientModel', but it could not be found

**Comment by joseharriaga** [comment]
Hello, @eliasandronicou . What version of System.ClientModel are you using?

**Comment by eliasandronicou** [comment]
1.1.0-beta.5

**Comment by joseharriaga** [comment]
@eliasandronicou  We're preparing to release a new version of the library in the next few days that will include the upgrade of the System.ClientModel dependency to version `1.1.0-beta.5`. For now, version `2.0.0-beta.7` of the OpenAI library uses System.ClientModel version `1.1.0-beta.4`, so if you switch to that version, the error should go away.

**Pull request merged**
